name: binding_example
description: example of binding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true